### DISCUSSION TITLE
Documentation on Jaeger / Opentracing / Opentelemetry

### DISCUSSION THREAD

**Discussion by slamer59** [saleor/saleor#10158] [Q&A] [answered]
Hello,
I am starting to deploy Jaeger for tracing Saleor application on both Core / Frontend. 

I saw that the documentation since v3 is more minimal than v2. It mentions Opentracing which is now an archived project and just mentioning **docker-compose** which is not for production. 

I also dive into the code to see to see where the metrics are stored but I just find opentracing `https://github.com/saleor/saleor/search?q=opentracing`

Can you give us a status on this ? Will it be supported ? How can I help to improve the documentation / code ? etc. 

For what I see, the best option (for me) would be to :
- migrate to [opentelemetry](https://opentelemetry.io/docs/migration/opentracing/)
- Deploy with a sidecar instead of dedicated agent. 
- improve documentation to at least show what can be monitored. 

Thanks for your work on Saleor :)

**Comment by patrys** [comment, marked as answer]
We will eventually migrate to OpenTelemetry. It's not currently our top priority since the existing solution works.

Sidecars are tricky because in most setups you'll want either one Agent per host or one per service, not one per running pod.

Good call on the docs, to see what data is available, you can give [Jaeger](https://docs.saleor.io/docs/3.x/developer/running-saleor/monitoring#jaeger) a try.

**Comment by slamer59** [comment]
Hello, thanks for your feedback. 
It was hard for me to use Jaeger as it is. 
For local development it worked but for deployment it was more a pain since I had to learn Jaeger / Opentelemetry / opentracing in k8s environment. Some of the documentation was obsolete too :) 

It is still not production ready but a first trial. I succeed to install it with : 
- sidecar allinone Jaeger
- Jaeger operator
- saleor 
- opentelemetry (with opentracing shim)

Basic steps : 
1- Deploy Jaeger Operator  
2- Deploy Jaeger
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne # <1>
  allInOne:
    image: jaegertracing/all-in-one:latest # <2>
    options: # <3>
      log-level: debug # <4>
  storage:
    type: memory
    options: 
      memory:
        max-traces: 100000
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  ingress:
    enabled: false    
    # serviceType: LoadBalancer
```
3- Deploy custom Saleor core

For Saleor : 
- add requirements opentelemetry-api, opentelemetry-sdk, opentelemetry-exporter-jaeger, opentelemetry-instrumentation-django, opentelemetry-instrumentation-asgi
- instrument wsgi / asgi application with [**OpenTelemetryMiddleware** ](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/asgi/asgi.html) 
- Replace **jaeger_client** (opentracing) by otel client
- add Jaeger exporter

```python
trace.set_tracer_provider(
    TracerProvider(resource=Resource.create({SERVICE_NAME: "saleor-core-service"}))
)
OTEL_TRACER = trace.get_tracer(__name__)

# create a JaegerExporter
JAEGER_EXPORTER = JaegerExporter(
    # configure agent
    # agent_host_name='localhost', # OTEL_EXPORTER_JAEGER_AGENT_HOST
    # agent_port=6831, # OTEL_EXPORTER_JAEGER_AGENT_PORT
    # optional: configure also collector
    # collector_endpoint='http://jaeger-collector:14268/api/traces?format=jaeger.thrift', # OTEL_EXPORTER_JAEGER_ENDPOINT
    # username=xxxx, # optional OTEL_EXPORTER_JAEGER_USER
    # password=xxxx, # optional OTEL_EXPORTER_JAEGER_PASSWORD
    # max_tag_value_length=None # optional OTEL_EXPORTER_JAEGER_TIMEOUT
    # udp_split_oversized_batches=None, OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES
)

OTEL_TRACER_PROVIDER = trace.get_tracer_provider()
OTEL_TRACER_PROVIDER.add_span_processor(BatchSpanProcessor(JAEGER_EXPORTER))
if DEBUG:
    OTEL_TRACER_PROVIDER.add_span_processor(BatchSpanProcessor(ConsoleSpanExporter()))

# Create an OpenTracing shim.
OPENTRACING_SHIM = create_tracer(otel_tracer_provider=OTEL_TRACER_PROVIDER)
```


- Replace opentracing tracer everywhere with something like 

```python
from django.conf import settings
shim = settings.OPENTRACING_SHIM
with shim.start_active_span(operation) as scope:
   ... 
```

Not sure about sidecar. It seems that it is more suited for loadbalancing compared to DaemonSet when I read the architecture. 

https://www.jaegertracing.io/docs/next-release/architecture/
https://www.jaegertracing.io/docs/next-release/operator/#installing-the-agent-as-daemonset

Anyway, when this will be more a priority, I would see how I can contribute !
