### DISCUSSION TITLE
Thumbnail Generation - url points to localhost:8000 and not domain/image host

### DISCUSSION THREAD

**Discussion by Horib** [saleor/saleor#11117] [Deployment] [answered]
Hi everyone, I posted a question on Saleor Dashboard Discussions, but now that I think about it, my problem is more Saleor Core related than Dashboard.

Hopefully someone can help :)

https://github.com/saleor/saleor-dashboard/discussions/2505#discussion-4521859

I have a thumbnail error, I'm hosting my images on a S3 bucket and using CloudFront to server the images, that works fine.
My  thumbnails on the other hand do not, and if i add a size to my media images they do not work either.

Problem is normally i get a url from CloudFront, but for thumbnails and changed media images i get a http://localhost path
See images below
![msedge_pBt2B4jQef](https://user-images.githubusercontent.com/25446543/198880205-c17527f6-802b-4cc4-b5b5-2104f651e4bc.png)
![msedge_Wqcm901bAY](https://user-images.githubusercontent.com/25446543/198880209-54a2d21a-fdaa-4198-9f70-82bae4da46af.png)

I run Saleor Core in a docker via docker-compose + .yaml file and a Nginx server on Linux (Not docker)
I suspect my problems has something to do with Nginx and the thumbnails/images  not "building" or "generating"???

```ruby
upstream core {
        server localhost:8000;
}

server {

        server_name ---DOMAIN_HERE--- www.---DOMAIN_HERE---;

        location / {
                include proxy_params;
                proxy_pass http://core/;
        }
		location /graphql/ {
                include proxy_params;
                proxy_pass http://core/graphql/;
        }

# This probably does not work
        location /media/ {
                alias /app/media/;
        }

# This probably does not work
        location /thumbnail/{
                include proxy_params;
                proxy_pass http://core/;
        }

# I can access this route but mailhog does not recieve any emails as of yet, not sure it is working then?
        location ^~ /mailhog/ {
				chunked_transfer_encoding on;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:8025/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_redirect off;
                proxy_buffering off;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/---DOMAIN_HERE---/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/---DOMAIN_HERE---/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.---DOMAIN_HERE---/) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = ---DOMAIN_HERE---/) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;    

        server_name ---DOMAIN_HERE--- www.---DOMAIN_HERE---;
    return 404; # managed by Certbot
	
}

```

**Comment by magul** [comment]
Hi, I may be wrong, but it doesn't look like a problem with nginx, as I believe full URLs exposed by GraphQL are build in Django. They are based (or at least should be) on media storage class you're using.

Just to re-create it, can you share:
 * what Saleor vesion you're running?
 * what's your configuration around these lines: https://github.com/saleor/saleor/blob/42ca64b2f690d10e233a7964bfe5971b9ea0e800/saleor/settings.py#L440 (as they govern, how S3 storage backend calculate urls)?

**Comment by fowczarek** [comment]
Hi @Horib, 

Do you have configured any workers? 

All async tasks are processed by workers to not overload the server. 
You could set worker by `CELERY_BROKER_URL`. More info [here](https://docs.saleor.io/docs/3.x/developer/running-saleor/configuration#celery_broker_url).

The thumbnails are generated on-demand. You could read more about thumbnails [here](https://docs.saleor.io/docs/3.x/developer/thumbnails#generating-the-thumbnails).

**Comment by Horib** [comment]
@magul 
I have not done any changes to the code within Saleor Core, only via env file, docker-compose and nginx 
- My Saleor Core Version atm is 3.8.0-a

@fowczarek 
I have a worker within the docker-compose I havnet touched it, It is a good chance it has not been configured right.
I am unsure in how i should configure the `CELERY_BROKER_URL`
I was under the assumption that the thumbnails generate command was removed? 
- At least i get an error when i use the command `docker-compose run --rm api python3 manage.py create_thumbnails`

I posted both my .env file and docker-compose.yml see below, maybe there is something really obvious that i am missing or doing worng. :) 

My Env file atm
```
ALLOWED_HOSTS='---IP ADDRESSES---'
ALLOWED_CLIENT_HOSTS=---DASHBOARD-URL, CLOUDFRONT-URL
DATABASE_URL=postgres://saleor:saleor@db/saleor
DEBUG=False

# These are not in use atm
# --------------------------------------------
# NODE_MODULES_CACHE=false
# NPM_CONFIG_PRODUCTION=false
# ALLOWED_CLIENT_HOSTS=False
# DEFAULT_FROM_EMAIL=noreply@example.com
# CELERY_BROKER_URL=redis://redis:6379/1
# --------------------------------------------

EMAIL_URL='smtp://---EMAIL---

SECRET_KEY='---KEY HERE---'
RSA_PRIVATE_KEY='---KEY HERE---'

CREATE_IMAGES_ON_DEMAND=False

AWS_ACCESS_KEY_ID=---KEY HERE---
AWS_SECRET_ACCESS_KEY=---KEY HERE---
AWS_MEDIA_BUCKET_NAME=---S3 BUCKET NAME HERE---
# AWS_STORAGE_BUCKET_NAME=---S3 BUCKET NAME HERE---
AWS_QUERYSTRING_AUTH=True

AWS_STATIC_CUSTOM_DOMAIN=---CLOUDFRONT KEY---
AWS_MEDIA_CUSTOM_DOMAIN=---CLOUDFRONT KEY---
```

My docker-compose.yml file
```
version: "3.4"

services:
  api:
    ports:
      - 8000:8000
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      - ./saleor/saleor/:/app/saleor:z
      - ./saleor/templates/:/app/templates:z
      - ./saleor/tests/:/app/tests
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      # - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=---DASHBOARD-URL---
      - ALLOWED_HOSTS=localhost,api, + ---OTHER-IP'S--- + ---DOMAIN-URL--- + ---CLOUDFRONT-URL---

  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX

  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: "/static/"
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - .env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./saleor/saleor/:/app/saleor:Z,cached
      - ./saleor/templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:


networks:
  saleor-backend-tier:
    driver: bridge

```
