### DISCUSSION TITLE
Unexpected token + how to create dashboard user ?

### DISCUSSION THREAD

**Discussion by dayeggpi** [saleor/saleor#12277] [Deployment]
Hi team,

I am trying to setup a PROD solution.

I followed instructions from https://docs.saleor.io/docs/3.x/setup/docker-images
and deployed saleor as well as saleor-dashboard docker images.

When I go to my dashboard link I can see the login screen for the dashboard.

However : 

1- On that dashboard login page I see an error on top right "Unexpected token '<', "<html> <h"... is not valid JSON"

2- I have no idea how to setup a dashboard user (i couldnt find it in the doc)

3- I imagine that I also need to deploy react-storefront in order to get the actual storefront...

I am a bit lost with the documentation, could someone please give me small hints/tips to get me moving ?

Thanks !

**Comment by dayeggpi** [comment]
so maybe a bit more info : 

I installed saleor by having following docker-compose.yml : 

```
version: '3.7'
services:
  saleor:
    image: ghcr.io/saleor/saleor:latest
    container_name: saleor
    restart: always
    volumes:
      - ./shop:/shop/
```

then I isntalled salero-dashboard by having following docker-compose.yml :  

```
version: '3.7'
services:
  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.12.1
    container_name: "saleordashboard"
    hostname: "saleordashboard"
    restart: always
    environment:
      - API_URL=https://mydomain.com
    volumes:
      - ./shop:/shop/
```


when going to mydomain.com I see the following : 

https://imgur.com/a/owkhrtN


and from there, I have the 3 issues stated in original post
