### DISCUSSION TITLE
Login went wrong. Please try again.

### DISCUSSION THREAD

**Discussion by charleslcso** [saleor/saleor#17117] [Deployment]
Hello, I'm coming from OpenCart, and would like to try Saleor for all my future shops.

Just followed the official doc and got it installed. I think.

Saw the login dashboard, tried to login after creating a superuser, but it says "Login went wrong. Please try again."

The command and output from creating superuser is as follow:

`root@shop:/opt/saleor-platform# docker-compose run --rm api python3 manage.py createsuperuser`
`Creating saleor-platform_api_run ... done`
`2024-11-30 10:18:21,944 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1:MainThread]`
`Emailcharles@tourdefarm.com`
`Password: `
`Password (again): `
`Superuser created successfully.
`

What should I do to at least get the error?

PS: As I haven't set up any email services in Saleor yet, I can't reset passwords.

**Comment by 0xmd** [comment]
Sounds like previous issues such as https://github.com/saleor/saleor-platform/issues/298 - If so:
```
  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    ports:
      - 9000:80
    restart: unless-stopped
    environment:
      - API_URL=https://EXTERNAL_IP:8000/graphql/ # <-- use the IP you are using from your browser here with http/https
```
You can also debug using browser devtools.
