### DISCUSSION TITLE
Minimum Hardware Requirements

### DISCUSSION THREAD

**Discussion by itwasmee** [saleor/saleor#7172] [Deployment]
Hello,
I was wondering if you had some metrics regarding saleor-core performance usage, or if some sort of chart was available to predict deployment and running costs. What minimum requirements would you recommend for the smallest of shops for exemple ?
Thank you in advance

**Comment by manojLondhe** [comment]
We are also interested in knowing the recommended minimum config for these services
- api
- dashboard
- database

**Comment by g-londhe** [comment]
I'm interested in knowing this.

**Comment by simon-online** [comment]
Yes, I'd like to find out about peoples experiences with the optimal hosting for a small to medium sized store.

There are a number of separate containers with the default saleor-platform configuration. Does it work out cost effective to run so many containers for a smaller store?

Is it possible to host a Saleor store for around $100 per month?

Interested to find out if and how people are running a Saleor store on a smaller budget.

**Reply by timuric** [reply]
We are updating our pricing soon, so it would be possible to get a server-less setup under 100$

**Reply by Gldywn** [reply]
Hi @timuric, any ETA for this new server-less setup?

**Reply by patrys** [reply]
@0xWhiteleaf Timur is on a holiday break. We're currently rolling out the new Saleor Cloud pricing. Please allow a few weeks until it becomes public.

**Reply by Gldywn** [reply]
Thanks @patrys

**Comment by RocketRene** [comment]
I would also like to know this

**Comment by simon-online** [comment]
Hey @matteius and @wileyknight, what has your experience been with minimum hosting requirements?

**Comment by wileyknight** [comment]
I don't know how much help this will be but my setup is running on a dedicated Ubuntu 20.04 server with several other Next.js sites running on other ports.

I can tell you that you are going to want a good allocation of memory. Starting Saleor core took about a gig, running the dashboard takes another 3 gig, running my storefront took an extra 500 Mb. I would recommend you have at least 6 gig above your OS needs for running everything. That should cover the costs of SQL, Saleor core, dashboard, and your storefront as a minimum.

I've got 12 cores on a Xeon chip and I'm chugging an average of 10% use. I forget what the MHz is on the chip but it's about 5-7 years old. 

I'm not running Saleor in the recommended docker containers just straight js and python. Also, not using nginx. I'm on a VM and the proxy is handled by the server. That all said the overhead of running docker and nginx should be minimal. However running the saleor-platform will use more resources as it runs everything in a nice neat little package. I am already using postgreSQL for my other sites and don't need the extra overhead of jaeger, db, redis and worker. Not running those will keep your overhead down.

saleor takes up 592 Mb, dashboard 862, storefront 623 Mb >> Those estimates are after installation.

That being said you can get away with a relatively small SSD 128Gb, at least 6Gb of running ram for Saleor, dashboard and storefront and a decent processor... 6-8 cores is what I would recommend as a minimum but you can try less.

I'm running everything on a single server and like I said I've got other sites running in parallel with no problems. I'm also fetching data using Strapi as a CMS to Saleor. Running everything JS this way makes for fast response and low CPU, the biggest overhead is memory.

**Reply by simon-online** [reply]
Wow brilliant, thanks for all the details!

**Reply by tiendq** [reply]
How could dashboard takes 3Gb of memory? Storefront and dashboard are SPA and once they're built they're just a bulk of files. I'm only curious about Postgres database and core API which surely the more memory the better for them but initially I could run both for 2GB each (on separate Ubuntu 20.04 instances).

**Comment by matteius** [comment]
I am deployed to a Kubernetes cluster in DigitalOcean using managed Postgresql and managed redis instances.  My numbers are a little different than @wileyknight especially around the dashboard -- drastically so, to the point where I find it hard to believe, but I even made sure to access the dashboard and recheck -- its using only 10 Mi.  I have two copies of each service running (except for beat, that you should only ever have one) and I use topology constraints to ensure that the services spread evenly between my two nodes.  I find that the actual memory amount my production docker containers are using are:

saleor - ~750 Mb
Dashboard ~ 10 Mb
react-storefront ~ 150 Mb
Celery worker ~ 700 Mb
Celery Beat ~ 250 Mb

The actual numbers I got using kubectl top:

# Saleor backend
matteius@matteius-VirtualBox:~/mattscoinage$ kubectl top pod mattscoinage-xxxx -n whitewhale
NAME                            CPU(cores)   MEMORY(bytes)   
mattscoinage-xxxx   21m          746Mi           

# Saleor Dashboard
matteius@matteius-VirtualBox:~/mattscoinage$ kubectl top pod mattscoinage-dashboard-xxxx -n whitewhale
NAME                                      CPU(cores)   MEMORY(bytes)   
mattscoinage-dashboard-xxxx   0m           10Mi           

# React Storefront (my fork which is basically just styling changes)
matteius@matteius-VirtualBox:~/mattscoinage$ kubectl top pod mattscoinage-storefront-xxxx -n whitewhale
NAME                                       CPU(cores)   MEMORY(bytes)   
mattscoinage-storefront-xxxx   1m           138Mi           

# Celery worker
matteius@matteius-VirtualBox:~/mattscoinage$ kubectl top pod mattscoinage-worker-xxxx -n whitewhale
NAME                                CPU(cores)   MEMORY(bytes)   
mattscoinage-worker-xxxx   4m           652Mi    

# Celery Beat
matteius@matteius-VirtualBox:~/mattscoinage$ kubectl top pod mattscoinage-beat-xxxx -n whitewhale
NAME                                 CPU(cores)   MEMORY(bytes)   
mattscoinage-beat-xxxx   0m           208Mi

**Reply by matteius** [reply]
I'll add that for my K8s I specifically am setting the following memory constraints:
## Dasboard
```
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
```

## Saleor
```
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
```

## React-storefront
```
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
```

## Worker
```
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
```

## Beat
```
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
```

**Reply by simon-online** [reply]
Wow, thanks so much. Amazing amount of detail and very interesting to find out the different hosting set ups.

**Reply by simon-online** [reply]
I assume if you wanted you could set up Celery to also run on the Saleor backend container. Not sure if that would be cheaper though.

It sounds like you can also run it without the redis and worker containers as @wileyknight has done.

What do you lose by not using redis or a worker?

**Reply by matteius** [reply]
> I assume if you wanted you could set up Celery to also run on the Saleor backend container. Not sure if that would be cheaper though.

@simon-online As a side-car?  I am not sure that would be best practice for Docker which is to be 1:1 with production process.  If it were in a side-car would it take up more memory as well, because the major cost of the cloud providers here is the memory usage as CPU is fairly light.  I think since the saleor backend powers both the storefront and dashboard, having it isolated to its own container is worth it.  

> It sounds like you can also run it without the Redis and worker containers as @wileyknight has done.

Not sure what you mean -- I am definitely running Redis and database at production scale, which you would never want to run in a container IMO.  I am definitely using Redis and the worker though.

> What do you lose by not using Redis or a worker?

Not having the worker would be bad because you would loose tasks that optimize the images and cut them to different sizes and upload them to django-storages.  I am sure the worker also does other tasks as well, so not having that would be missing functionality.

You would loose caching not having Redis -- I haven't done a deep exploration yet what is being cached or if any other data structures are being used to optimize logic in the saleor backend, but I could look into what is being stored in my Redis cache at some point and report back.

**Reply by akhial** [reply]
Worker is required for core features.

See: https://github.com/saleor/saleor/discussions/8707#discussioncomment-1774303

**Reply by simon-online** [reply]
Oh right,  thanks for your answers @matteius and @akhial.

Redis could also be getting used with Celery as a broker and/or result store.

**Comment by simon-online** [comment]
An option I'm currently considering is to host the dashboard and storefront on Vercel which seems great value at $20 per month for any number of frontend sites, Dynamic edge caching and up to 1 TB of bandwidth per month! 

https://vercel.com/pricing

And then run the backend container(s) / Cloud SQL service (small shared) on Google Cloud Platform. I'm estimating that this set up should be about $150 per month or less.

**Reply by matteius** [reply]
I looked into Vercel too a little bit, but I am already heavily invested in Digital Ocean -- I spend 150$ a month running 5 sites in a cluster there where one is my saleor store.  DO is raising their prices in July but are still the most affordable cloud provider for what you get IMO.   I felt like one of the bigger limitations of the $20 plan is 5,000 source images but I am sure that is quite sufficient for the average store; Its a big leap to go to the next pricing structure in Vercel.  

The big reason for Vercel, which its still a black box for me, is they do some nextjs dynamic image stuff I guess that you don't get out of the box with regular cloud providers, BUT I found it was really easy to sub out an image loader with a custom one that just pulls it from the CDN I setup in DO -- that is where I have django-storages upload it to my S3 (called Spaces in Digital Ocean) and then the app pulls the cut image sizes from there, seems pretty efficient.  

 Additionally, I am not sure how Vercel is running it, but I would assume its pretty hard to get away from doing `pnpm run build` and `pnpm run start`.   Static builds would require you add logic to hit the Apollo client and pull the latest product data and compile a bunch of static pages that would not get updated until a new build + deployment.  This is the biggest limitation of the react-storefront and next.js stuff I have seen because you get really bad performance scores running with a dynamic pnpm run start.  Though in practice it performs rather well if you have a good internet connection and the biggest performance impact I had was when the pnpm server was trying to handle the images itself, there were massive lag times and it was much better pulling that out to the CDN.

**Reply by simon-online** [reply]
Yeah, totally makes sense if you already have a hosting set up that you can make use of.

The 5,000 source images restriction is definitely something to consider. For any additional source images it's charged at $9 per 1,000 when you stay on the $20 plan.

Good to know that the image loader was easy to sub out for a CDN though.

I think Vercel must have another way of running a frontend that doesn't have the performance issues of pnpm.

**Reply by matteius** [reply]
@simon-online I mean if we knew a react-storefront saleor site running in vercel we could feed the URL into https://web.dev/measure/ and verify if the performance is actually any better than pnpm.  My deployed site was having some major performance issues on the new saleor 3.4.6 but I just rolled back to 3.4.5 and it seems to be doing well again.  FWIW my saleor site scores like this on 3.4.5:
![image](https://user-images.githubusercontent.com/479892/174446133-1108e71a-4698-4479-8f03-0db0719cd9a6.png)
I usually get a 100 on Best Practices, but I see I didn't totally resolve one of my merge conflicts with react-storefront properly and there is a console error, but I can fix that soon.

**Reply by simon-online** [reply]
Could you test your exact same storefront on the free Vercel Hobby plan?
That would definitely be an interesting comparison.

**Reply by timuric** [reply]
>  Static builds would require you to add logic to hit the Apollo client and pull the latest product data and compile a bunch of static pages that would not get updated until a new build + deployment.

`react-storefront` is not rendering pages on build time, we are using [fallback: blocking](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration#generating-paths) 
This means that pages are generated on request with time to live up to 1 minute (which you can change to anything you like)

> This is the biggest limitation of the react-storefront and next.js stuff I have seen because you get really bad performance scores running with a dynamic pnpm run start.

`pnpm start` doesn't give you global edge caching as Vercel deployment would, this means there would be extra latency, and each request also needs processing time. In order to speed it up you would at least need to add an image CDN which would cost you extra. 

Overall if you care about performance, I believe Vercel + Saleor Cloud would give you the best performance, developer experience, save you maintenance effort, and probably would be also cheaper than DO. 

I know we don't have hobby/small-store friendly Saleor Cloud plan yet, but feel free to reach out on Twitter if you are interested in one.

**Comment by wileyknight** [comment]
@matteius I don't know how our memory is so off. I measured my consumption by the actual usage from my VM. I rebooted the server and brought up the services one by one measuring the amount of actual memory that the whole server was consuming.

**Reply by matteius** [reply]
I am sure something is up with the 10 Mi number because I definitely allocate min of 256 Mi and max of 512 Mi -- that being said I am sure that running the dashboard can be done on 512 Mi or less.

**Reply by wileyknight** [reply]
It's just crazy that I am sucking up 3 gig of ram on the dashboard. I don't really care. It is my own dedicated server with 64 gig installed but it's still a lot.

**Reply by timuric** [reply]
@matteius you don't need any servers to serve the dashboard, it can be hosted as a static file as any SPA

**Reply by patrys** [reply]
Please ensure you are not running either the dashboard or the storefront in development mode. That does take gigabytes of memory as it supports hot reloading of components while you edit the code.

**Reply by matteius** [reply]
Got my dashboard application running behind a CDN today as a SPA and removed the docker deploy.  It didn't actually free up any memory on the cluster which leads me to believe it was running with 10 mi in the docker container, but at least in theory this frees up resources on my cluster.   Its pretty slick to do it this recommended way, and I'll share what I figured out (Digital Ocean flavored):

Step 0:  Pick two sub-domains.  Example: `admin.your-dns.net` and `admin-cdn.your-dns.net`

Step 1: Setup a Digital Ocean spaces and enable the CDN component, assign your `admin-cdn.your-dns.net` DNS

Step 2:  Create and apply these K8 patterns for the External Service and the ingress-nginx rules
Use an `ExternalName` to have a service that ingress-nginx can route the nginx rule to that passes through to the CDN.
```
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: project-namespace
  labels:
    app: dashboard
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
    service.beta.kubernetes.io/do-loadbalancer-name: "your-dns.net"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
spec:
  type: ExternalName
  externalName: admin-cdn.your-dns.net
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 443
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: project-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "admin-cdn.your-dns.net"
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
    nginx.ingress.kubernetes.io/proxy-body-size: "12m"
    nginx.org/client-max-body-size: "12m"
spec:
  tls:
    - hosts:
          - admin.your-dns.net
      secretName: yourDNS-admin-tls
  rules:
  - host: admin.your-dns.net
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: dashboard
              port:
                number: 80
```

To build the dashboard version I want to deploy, I use this script:
```
export API_URI="https://api.your-dns.net/graphql/"
export APP_MOUNT_URI="/"
export STATIC_URL="https://admin-cdn.your-dns.net/"
cd saleor-dashboard
rm -rf build/
npm run build
```

Then you can use boto3 or manually upload the files as publicly accessible to your CDN.
