### DISCUSSION TITLE
Jaeger metrics not get published for Saleor v3.0 production setup

### DISCUSSION THREAD

**Discussion by gauravraj** [saleor/saleor#9087] [Deployment]
I'm using Azure for hosting Saleor v3.0. I've used following setup in production - 

**Machine 1**
Hosted Component: Postgres
Domain: postgres.example.com 

**Machine 2**
Hosted Component: Redis
Domain: redis.example.com

**Machine 3**
Hosted components: Mailhog and Jaeger
Domain: saleor-others.example.com

**Machine 4**
Hosted Components: Saleor API, Saleor Dashboard
Domain: saleor3.example.com

**Docker Compose Configuration**
```
version: "2"

services:
  api:
    image: gauravrajvirgo917/saleor3-prod:3.01
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-prod-tier
    environment:
      - DATABASE_URL=postgres://username:password@postgres.example.com/postgres?sslmode=require 
      - DEFAULT_FROM_EMAIL=noreply@example.com 
      - CELERY_BROKER_URL=redis://:@redis.example.com:6379/1 
      - SECRET_KEY=saleorprod
      - EMAIL_URL=smtp://saleor-others.example.com:1025 
      - REDIS_URL=redis://:@redis.example.com:6379/1 
      - ALLOWED_HOSTS=localhost,127.0.0.1,saleor3.example.com
      - ALLOWED_CLIENT_HOSTS=localhost,127.0.0.1,saleor3.example.com
      - API_URI=http://saleor3.example.com:8000/graphql/ 
      - CREATE_IMAGES_ON_DEMAND=False 
      - DEFAULT_COUNTRY=IN 
      - DEFAULT_CURRENCY=INR 
      - JAEGER_AGENT_HOST=saleor-others.example.com 
      - JAEGER_LOGGING=True 
      - JAEGER_AGENT_PORT=6831  

  dashboard:
      build:
        context: ./saleor-dashboard
        dockerfile: ./Dockerfile.dev
      ports:
        - 9000:9000
      restart: unless-stopped
      environment:
        - API_URI=http://saleor3.example.com:8000/graphql/
      volumes:
        - ./saleor-dashboard/:/app:cached
        - /app/node_modules/
      command: npm start -- --host 0.0.0.0 --disable-host-check  

networks:
  saleor-prod-tier:
    driver: bridge
```

I've installed Jaeger examples on Machine4 to see if they can publish metrics to Machine3. This seems to be working. 
I've also checked the ports and they are open. 

Saleor publishes logs for that it's sending events to Jaeger but somehow it's not visible in Jaeger dashboard. How can I debug this issue?

After experimenting on it a bit in local, I can see that it's not a docker issue as I was suspecting.

When I'm testing the service locally and starting the service using
`python3 manage.py runserver 0.0.0.0:8000`
It is able to send the events to Jaeger but when I start the same service using -
`gunicorn --bind :8000 --workers 4 --worker-class saleor.asgi.gunicorn_worker.UvicornWorker saleor.asgi:application`
It doesn't seem to be working.
