### ISSUE TITLE
Bug: 502 HTTP Status Not Found: / Warning

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor#11492]
### What are you trying to achieve?

Run Saleor in production mode on GKE Autopilot.

### Steps to reproduce the problem

1. Build, configure and deploy Saleor backend to work on GKE Autopilot with DEBUG turned on.
2. Test Saleor API and observe it working.
3. Update the DEBUG environment variable to turn off DEBUG mode and re-deploy.
4. Test Saleor API and observe it is no longer working and all requests are returning with a 502 HTTP status and server logging has numerous "Not Found: /" warning messages.

<img width="840" alt="Screen Shot 2022-12-14 at 11 37 43 pm" src="https://user-images.githubusercontent.com/10040020/207597197-11516873-0f15-472e-8d53-16db5e3e2d4f.png">
<img width="534" alt="Screen Shot 2022-12-14 at 11 33 23 pm" src="https://user-images.githubusercontent.com/10040020/207596836-ce61b958-2196-49dc-bc0a-07ab86de2d52.png">

Example environment variables stored as secret (test-backend-secrets-live)
```
ALLOWED_CLIENT_HOSTS=www.test.com,dash.test.com,test.com,test.com,dash.test.com,dev.test.com,test-dashboard.vercel.app,localhost
ALLOWED_HOSTS=*
DEBUG=False
DATABASE_URL=postgres://db_user:db_password@xxx.xx.xxx.xx:5432/test-db
CACHE_URL=redis://xxx.xx.xxx.xx:6379/0
CELERY_BROKER_URL=redis://xxx.xx.xxx.xx:6379/1
EMAIL_URL=submission://backend@ms.test.com:xxxxxxxxxx-xxxxxxxxx-xxxxxxxx@smtp.mailgun.org
SECRET_KEY=secret_key
JWT_TTL_ACCESS=1d
DEFAULT_FROM_EMAIL=orders@test.com
GOOGLE_APPLICATION_CREDENTIALS=/secrets/cloudstorage/test-backend-credentials.json
GS_MEDIA_BUCKET_NAME=test-media
GS_BUCKET_NAME=test-static
DEFAULT_CHANNEL_SLUG=default-channel
DEFAULT_COUNTRY=AU
DEFAULT_CURRENCY=AUD
STOREFRONT_URL=https://test.com/
DASHBOARD_URL=https://dash.test.com/
```

Generate RSA private key as follows:
```openssl genrsa -out rsa-private-key.pem 3072```

Upload RSA private key as secret:
```kubectl create secret generic rsa-private-key --from-file=rsa-private-key.pem```

RSA_PRIVATE_KEY environment variable is getting set separately with rsa-private-key secret:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
  labels:
    app: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: saleor-api
        # Replace  with your project ID or use `make template`
        image: us-central1-docker.pkg.dev/test-web/test-repository/saleor-api:v3.9.4
        resources:
          requests:
            memory: "750Mi"
            cpu: "125m"
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        env:
          - name: RSA_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: rsa-private-key
                key: rsa-private-key.pem
        envFrom:
          - secretRef:
              name: test-backend-secrets-live
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: test-backend-credentials
            mountPath: /secrets/cloudstorage
            readOnly: true
      - name: saleor-worker
        # Replace  with your project ID or use `make template`
        image: us-central1-docker.pkg.dev/test-web/test-repository/saleor-api:v3.9.4
        resources:
          requests:
            memory: "750Mi"
            cpu: "125m"
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        command: ["celery", "-A saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel=info", "-B"]
        env:
          - name: RSA_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: rsa-private-key
                key: rsa-private-key.pem
        envFrom:
          - secretRef:
              name: test-backend-secrets-live
        volumeMounts:
          - name: test-backend-credentials
            mountPath: /secrets/cloudstorage
            readOnly: true

      volumes:
        - name: test-backend-credentials
          secret:
            secretName: test-backend-credentials
```

### What did you expect to happen?

Saleor to be running in production mode with no warnings or server error status codes.

### Environment

Saleor version: v3.9.4
OS and version: Docker build on GKE Autopilot
