### ISSUE TITLE
Bug: Playground is requesting non-secured /graphql/ URL

### ISSUE THREAD

**Issue by madmonkeyworks** [saleor/saleor#14983]
### What are you trying to achieve?

We are deploying Saleor Core with Docker. 
The problem is that the playground requests resources from HTTP instead of HTTPS, although we clearly stated the environment variables to use HTTPS versions or URLs.
Getting a "mixed content" error in browser.

Help is much appreciated

### Steps to reproduce the problem

1. Download official dockerized Saleor Core version 3.17.2
2. Set environment variables in backend.env file

```
CELERY_BROKER_URL=redis://redis:6379/1
DATABASE_URL=<path to database>
DEFAULT_FROM_EMAIL=noreply@example.com
EMAIL_URL=smtp://mailpit:1025
API_URI=https://<path to saleor core>/graphql/
API_URL=https://<path to saleor core>/graphql/
GRAPHQL_ENDPOINT=https://<path to saleor core graphql api>/graphql/
SECRET_KEY=changeme
PLAYGROUND_ENABLED=True
ENABLE_SSL=True
PUBLIC_URL=https://<path to saleor core graphql api>
SECURE_SSL_REDIRECT=True
DEBUG=True
ALLOWED_CLIENT_HOSTS=<path to saleor core>
ALLOWED_HOSTS=api,<path to saleor core>
DASHBOARD_URL=https://<path to dashboard>
ALLOWED_GRAPHQL_ORIGINS=*
RSA_PRIVATE_KEY=<private key>
```

3. Set environment variables in common.env file

```
DEFAULT_CHANNEL_SLUG=default-channel
HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS=True
HTTP_IP_FILTER_ENABLED=True
```

4. Modify docker-compose.yml

```
version: "3.4"
 
services:
  api:
    image: ghcr.io/saleor/saleor:3.17.2
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
 
  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data
 
  worker:
    image: ghcr.io/saleor/saleor:3.17.2
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
 
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
 
  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier
 
volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:
 
networks:
  saleor-backend-tier:
    driver: bridge
```

7. Build Docker images
8. Run docker with compose up
9. Open playground on https://<path to saleor core>/graphql/
10. Inspect the requests in the browser 

**Result from browser inspect** 
```
useFetcher.tsx:15 Mixed Content: The page at '
[https://<path to saleor core>/graphql/'](https://<path to saleor core>/graphql/%27)
was loaded over HTTPS, but requested an insecure resource '
[http://<path to saleor core>/graphql/'.](http://<path to saleor core>/graphql/%27.)
This request has been blocked; the content must be served over HTTPS.
```

### What did you expect to happen?

GraphQL playground loading schema and requests working over HTTPS.

### Environment

Saleor version: 3.17.2
OS and version: Docker
