### ISSUE TITLE
Bug: Playground does not use PUBLIC_URL during rendering

### ISSUE THREAD

**Issue by jakub-borusewicz** [saleor/saleor#16810]
### What are you trying to achieve?

Access playground even if API is hidden behind reverse proxy

### Steps to reproduce the problem

1. Setup Saleor as a container in `docker-compose.yaml`, without exposing it to host machine, and rather through api gateway

```
services:
  saleor:
    image: ghcr.io/saleor/saleor:3.20
    expose:
      - "8000"
    networks:
      - api-gateway-network
    ...
  api_gateway:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - api-gateway-network
    depends_on:
      - saleor
    ...
```
- run docker compose
-  Open Saleor in browser -> Inspect -> Network
- go to playground in browser
result:
![image](https://github.com/user-attachments/assets/fe0d3fa3-f204-431a-b705-a32d7945b3a2)

### What did you expect to happen?

I would expect docs to be properly displayed

### Logs

Retrieving grapql schema fails
![image](https://github.com/user-attachments/assets/ea7549fc-e312-4f03-bbcc-8f8399d13863)

This is probably because playground is rendered with api_url based on request absolute uri
https://github.com/saleor/saleor/blob/main/saleor/graphql/views.py#L126

I would expect it to be based on PUBLIC_URL if it is set.

I'll issue pull request for that shortly

### Environment

Saleor version:: 3.20
OS and version: 6.6.52-1-MANJARO
