### ISSUE TITLE
Bug: Unable to access GraphQL API and Dashboard using docker

### ISSUE THREAD

**Issue by looped-monk** [saleor/saleor#17734]
### What are you trying to achieve?

I'm using docker to build API, dashboard and storefront. I'm deployed on Amazon Ec2 with a public IP http://3.xx.xx.xx/

I downloaded the latest release(using the verified tags) of the code because I had to put in my own logos. The logos are the only thing I have replaced. Code remains as is. Hence I modified the docker-compose.yml a built a custom docker Image using the dockerFile.

I'm able to access the dashboard but unable to login with a spinning icon appearing indicating a forever loading symbol. This is after I successfully apply migrations and populate db and create a superuser.
2.The API doesn't load either on http://3.xx.xx.xx:8000/graphql/ and keeps forever spinning in the browser address.

There is an issue with SECRET_KEY Not set when I apply migrations.
In the docker compose logs, I do see the environment variables getting replaced like Setting API_URL to http://3.xx.xx.xx:8000/

All the containers are running as well.

Here is my configuration :
```

version: "3.4"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./saleor/
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://3.xx.xx.xx:9000/
      - ALLOWED_HOSTS=localhost,api,3.xx.xx.xx

  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./saleor-dashboard/
    ports:
      - 9000:80
    restart: unless-stopped
    env_file:
      - backend.env

  db:
    image: library/postgres:15-alpine
    hostname: 172.16.16.4
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - POSTGRES_DB=saleor

  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.20
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - redis
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge

```

```
backend.env

CELERY_BROKER_URL=redis://redis-db:6379/1
DATABASE_URL=postgres://saleor:saleor@172.16.16.4:5432/saleor
DEFAULT_FROM_EMAIL=noreply@example.com
EMAIL_URL=smtp://mailpit:1025
SECRET_KEY=Have put a secret key here.
API_URL=http://3.xx.xx.xx:8000/graphql/
```

dockerFile for dashboard

FROM node:20-alpine as builder
RUN apk --no-cache add bash
WORKDIR /app
COPY package*.json ./
ENV CI 1
RUN npm ci --legacy-peer-deps

COPY nginx/ nginx/
COPY assets/ assets/
COPY locale/ locale/
COPY scripts/ scripts/
COPY vite.config.js ./
COPY tsconfig.json ./
COPY *.d.ts ./
COPY schema.graphql ./
COPY introspection.json ./
COPY introspection*.json ./
COPY .featureFlags/ .featureFlags/

COPY src/ src/

ARG API_URL
ARG APP_MOUNT_URI
ARG APPS_MARKETPLACE_API_URL
ARG EXTENSIONS_API_URL
ARG APPS_TUNNEL_URL_KEYWORDS
ARG STATIC_URL
ARG SKIP_SOURCEMAPS
ARG LOCALE_CODE

ENV API_URL ${API_URL:-http://localhost:8000/graphql/}
ENV APP_MOUNT_URI ${APP_MOUNT_URI:-/dashboard/}
ENV APPS_MARKETPLACE_API_URL ${APPS_MARKETPLACE_API_URL:-https://apps.saleor.io/api/v2/saleor-apps}
ENV EXTENSIONS_API_URL ${EXTENSIONS_API_URL:-https://apps.saleor.io/api/v1/extensions}
ENV APPS_TUNNEL_URL_KEYWORDS ${APPS_TUNNEL_URL_KEYWORDS}
ENV STATIC_URL ${STATIC_URL:-/dashboard/}
ENV SKIP_SOURCEMAPS ${SKIP_SOURCEMAPS:-true}
ENV LOCALE_CODE ${LOCALE_CODE:-EN}
RUN npm run build

FROM nginx:stable-alpine as runner
WORKDIR /app

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/replace-env-vars.sh /docker-entrypoint.d/50-replace-env-vars.sh
COPY --from=builder /app/build/ /app/

LABEL \
  org.opencontainers.image.title="saleor/saleor-dashboard" \
  org.opencontainers.image.description="A GraphQL-powered, single-page dashboard application for Saleor." \
  org.opencontainers.image.url="https://saleor.io/" \
  org.opencontainers.image.source="https://github.com/saleor/saleor-dashboard" \
  org.opencontainers.image.revision="$COMMIT_ID" \
  org.opencontainers.image.version="$PROJECT_VERSION" \
  org.opencontainers.image.authors="Saleor Commerce (https://saleor.io)" \
  org.opencontainers.image.licenses="BSD 3"

Kindly note, I have http not https. I'm assuming this isn't an issue.

Help appreciated.

### Steps to reproduce the problem

1. Download the latest code for saleor core and saleor dashboard using the verfied release tag.
2. Use docker compose.yml and build the containers using the dockerFIle provided for the above repos using the environment files as provided
3. Perform migrations and populate database and createsuperuser

### What did you expect to happen?

1.Successful dashboard login
2.Successful opening of API at http://3x.xx.xx.xx:8000/graphql/

### Environment

Saleor version: …
OS and version: …
